#!/bin/bash
# 
# 2023 FRC Software Rescue USB -
# A script to download all of the essential software packages for programming
# and FRC Robot in Java or C++, with the intention of creating a
# "rescue" USB drive for use at schools or events where the Wifi or Cellular
# internet service is pretty slow.
#

# the FRC manual
URLS=https://firstfrc.blob.core.windows.net/frc2023/Manual/2023FRCGameManual.pdf

# The required 2023 FRC game tools: roborio imager, driverstation, etc.
URLS="$URLS https://download.ni.com/support/nipkg/products/ni-f/ni-frc-2023-base-suite/23.0/offline/ni-frc-2023-base-suite_23.0.0.49182-0+f30_offline.iso"

# FRC Radio Imaging Tool for 2023
URLS="$URLS https://firstfrc.blob.core.windows.net/frc2023/Radio/FRC_Radio_Configuration_23_0_2.zip"

# WPILib - for programming in C or Java
URLS="$URLS https://github.com/wpilibsuite/allwpilib/releases/download/v2023.4.1/WPILib_macOS-Intel-2023.4.1.dmg"

URLS="$URLS https://github.com/wpilibsuite/allwpilib/releases/download/v2023.4.1/WPILib_macOS-Arm64-2023.4.1.dmg"

URLS="$URLS https://github.com/wpilibsuite/allwpilib/releases/download/v2023.4.1/WPILib_Linux-2023.4.1.tar.gz"

URLS="$URLS https://github.com/wpilibsuite/allwpilib/releases/download/v2023.4.1/WPILib_Windows-2023.4.1.iso"

# WPILib Add-ons
# CTRE
URLS="$URLS https://github.com/CrossTheRoadElec/Phoenix-Releases/releases/download/v5.30.4.2/CTRE_Phoenix_Framework_v5.30.4.2.exe"

URLS="$URLS https://github.com/CrossTheRoadElec/Phoenix-Releases/releases/download/v5.30.4.2/CTRE_Phoenix_FRC_Linux_5.30.4.zip"

URLS="$URLS https://github.com/CrossTheRoadElec/Phoenix-Releases/releases/download/v5.30.4.2/CTRE_Phoenix_FRC_macOS_5.30.4.zip"

# Rev
URLS="$URLS https://github.com/REVrobotics/REV-Software-Binaries/releases/download/revlib-2023.1.3/REVLib-offline-v2023.1.3.zip"

# NavX
URLS="$URLS https://dev.studica.com/maven/release/2023/NavX-Offline-2023-0-3.zip"

# PlayingWithFusion
URLS="$URLS https://www.playingwithfusion.com/include/getfile.php?fileid=7140"

# todo VSCode, for programming in C++ or Java

URLS="$URLS https://github.com/PhotonVision/photonvision/releases/download/v2023.3.0/photonvision-v2023.3.0-linuxarm64-image_RaspberryPi.xz"

URLS="$URLS https://github.com/PhotonVision/photonvision/releases/download/v2023.3.0/photonvision-v2023.3.0-linuxarm64-image_limelight2.xz"

URLS="$URLS https://github.com/balena-io/etcher/releases/download/v1.14.3/balenaEtcher-Setup-1.14.3.exe"

mkdir -p downloads
cd downloads

if [ $1 == --preview ]
then
    preview=1
else
    preview=0
fi

options="-nc --progress=bar "

for f in $URLS
do
    echo $f
    if [ $preview == 0 ]
    then
	wget $options $f
    fi
done
